[package]
name = "parser_utils"
version = "0.1.0"
authors = ["Sebas Arriola <sebdeveloper6952@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
